### ISSUE TITLE
 [Deployment] v1.7 discussion

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1059]
Issue for discussing what to include in the next version. This is not supposed to be a changelog or complete backlog. It is used primarily as a working document for deciding scope.

# Version goals/scope

- ..

# TODOs

## Store-related
- [ ] Version bump to v1.7
- [ ] Snip a version for TestFlight / Alpha to go through beta review
- [ ] Create new store versions
- [ ] (Optional) Update store assets/text/screenshots

## Features/fixes
- ..
