### ISSUE TITLE
Vise billettdetaljer og QR-kode kun på mobiler som er registrert som et aktivt "mobiltoken"

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1089]
- [x] #1653
- [x] #1661

## Opprinnelse

Krav fra Entur + I tråd med avklaringer om idbasert-konsept hos AtB avklart i møte 17.3.21 med bl.a. Grethe.

## Motivasjon

En gitt billettkonto skal bare være tilgjengelig fra én mobiltelefon av gangen. Vi må derfor skille mellom to tilstander: 
- **Mobilen er registrert som et aktivt "token" på kundens konto:** Billettene skal da vises på normal måte - slik at de kan vises fram til sjåfør ved ombordstigning, og slik at QR-kode kan vises fram til kontrollør. 
- **Mobilen er ikke registrert som "token" på kundens konto, eller er ikke et aktivt "token":** Billettene skal ikke vises, eller skal evt vises på en slik måte at det er tydelig at de ikke kan brukes ved ombordstigning eller kontroll. 

Denne saken må etterfølges av https://github.com/AtB-AS/mittatb-app/issues/1090 før vi kan rulle ut funksjonaliteten til kunder. Sakene er delt opp for å unngå å gape over for mye på en gang - både for design og implementasjon.

## Hypoteser og antagelser

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

### Har aktivt mobiltoken:

<img width="829" alt="Skjermbilde 2021-10-25 kl  10 42 33" src="https://user-images.githubusercontent.com/8980523/138663630-7e69b380-5f32-4d6f-9806-13958e4c48b0.png">

[Skisser](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6184%3A24932)
[Prototype](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=8%3A1960&node-id=6184%3A24932&viewport=406%2C48%2C0.72&scaling=scale-down&starting-point-node-id=6184%3A24932&show-proto-sidebar=1)

### Har t:kort som token:

<img width="922" alt="Skjermbilde 2021-10-25 kl  10 44 23" src="https://user-images.githubusercontent.com/8980523/138663886-00bc8df2-0d16-409f-b1bd-dbd4093ffaef.png">

[Skisser](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6190%3A23756)
[Prototype](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=8%3A1960&node-id=6190%3A23756&viewport=406%2C48%2C0.72&scaling=scale-down&starting-point-node-id=6190%3A23756&show-proto-sidebar=1)

## Akseptansekriterier

- [] Farger vises som forventet i både lys og mørk visningsmodus.
- [] Fungerer både for norsk og engelsk språk.
- [] Trekker ikke unødvendig batterikapasitet.
- [] Fungerer med opptil 200% fontstørrelse
- [] Kan brukes og forstås med skjermleser

**Comment by hildeor** [comment]
@jahnrohme Hvorfor ble denne lukket? Gjenstår fortsatt arbeid på denne.

**Comment by jahnrohme** [comment]
@hildeor De to punktene som skal gjøres i issuen ser ut til å være utført. Om det gjenstår arbeid, så tenker jeg disse blir fulgt opp i https://github.com/AtB-AS/mittatb-app/issues/1621?
Si ifra om du likevel fortsatt ønsker å gjenåpne denne.

**Comment by hildeor** [comment]
@jahnrohme Jeg tror akkurat den delen med egen knapp + bottom sheet for å vise i billettkontroll har falt mellom to stoler her, men jeg kan opprette en ny issue på det.

**Comment by jahnrohme** [comment]
Ahh, flott! 
Kjempebra du har øynene åpne for detaljene! Opprett gjerne en ny issue for akkurat det, ja :)
