### ISSUE TITLE
Fikse bugs og quickwins basert på tilbakemeldinger fra kunder

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1405]
Mål: Øke kundetilfredshet ved å fikse irritasjonsmomenter som koster oss lite å fikse. Synliggjør også at vi faktisk gjør forbedringer og tar tilbakemeldinger på alvor. 

Vi bør kun ta med endringer som tar mindre enn én dag å designe og implementere.

- [x] https://github.com/AtB-AS/mittatb-app/issues/1403 
- [x] https://github.com/AtB-AS/mittatb-app/issues/1401
- [x] https://github.com/AtB-AS/mittatb-app/issues/1392
- [x] https://github.com/AtB-AS/mittatb-app/issues/1393 (ikke etterspurt av kunder direkte, men vi får mange henvendelser fra kunder som ikke har fått med seg innholdet bak denne teksten)
- [x] https://github.com/AtB-AS/mittatb-app/issues/1451
- [ ] ~Vise flere enn 7 avganger pr linje @cbrevik~ 
- [x] La kunden velge type henvendelse før intercom
- [ ] Parameterendringer i reisesøk for å endre forslag med gange (sak i BFF)
- [ ]
