### ISSUE TITLE
[Feature] Gå over til OTP2 og kunne hente flere reiseforslag

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1790]
## Origin

_Links to received feedback, user research or other findings._

Vi har fått flere tilbakemeldinger om at reisesøk ikke er relevante og/eller at det er tungvint at man ikke kan kjapt laste inn flere reiseforslag. 

## TODOs

- #1848 
- #1944 

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

- [ ] Bruker kan selv switche mellom OTP1 og OTP2 (**skisse todo**)
- [ ] I OTP2 kan bruker hente inn flere reiseforslag i et allerede påstartet søk - brukerstyrt handling
- [ ] Ved reisesøk som medfører at motoren gjennomfører flere søk (i bakgrunnen) så lastes resultatene inn gradvis etter hvert som de blir funnet. Se prototype for demo
- [ ] Bruker får beskjed når man har nådd "maks-vinduet" for å utvide søket
- [ ] Loading-animasjon indikerer for bruker at det søkes etter flere reiser

Må avklares:

- [ ] Får vi til å beholde listen over søkeresultater når man beveger seg tilbake fra reisedetaljer?
- [ ] Ved refresh av listen: Er det raskt nok å beholde listen eller må vi tilbake til opprinnelig søkeresultat?

### Prototyper:
- [Finner få reiseforslag - opplevelse ved flere (automatiske) søk i bakgrunnen](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6414%3A29289&node-id=6577%3A48646&viewport=406%2C48%2C0.44&scaling=scale-down&starting-point-node-id=6577%3A48646&show-proto-sidebar=1)
- [Bruker laster inn flere reiseforslag - on demand](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6414%3A29289&node-id=6577%3A37140&viewport=406%2C48%2C0.44&scaling=scale-down&starting-point-node-id=6577%3A37140&show-proto-sidebar=1)
- [Finner ikke flere avganger (når maks innhenting)](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6414%3A29289&node-id=6577%3A40851&viewport=406%2C48%2C0.44&scaling=scale-down&starting-point-node-id=6577%3A40851&show-proto-sidebar=1)
- [Beholder listen ved navigering tilbake fra detaljvisning](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6414%3A29289&node-id=6577%3A42018&viewport=406%2C48%2C0.44&scaling=scale-down&starting-point-node-id=6577%3A42018&show-proto-sidebar=1)
- [Refresh av listen](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6414%3A29289&node-id=6577%3A43688&viewport=406%2C48%2C0.44&scaling=scale-down&starting-point-node-id=6577%3A43688&show-proto-sidebar=1)
- TODO: toggle

### Skisser:

- [Finner få reiseforslag - opplevelse ved flere (automatiske) søk i bakgrunnen](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6577%3A47734)
- [Bruker laster inn flere reiseforslag - on demand](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6577%3A40847)
- [Finner ikke flere avganger (når maks innhenting)](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6577%3A40848)
- [Beholder listen ved navigering tilbake fra detaljvisning](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6577%3A43368)
- [Refresh av listen](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6577%3A43631)

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by strombraaten** [comment]
Kan ikke den her egentlig lukkes nå? @hildeor @monopoint Eller må vi kanskje vente til reisesøket har blitt erstatta i 1.17-releasen?

**Comment by hildeor** [comment]
Jeg tenker denne kan lukkes.
