### ISSUE TITLE
Reisesøkforslag OTP1 vs OTP2

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1956]
Samler fortløpende innsikt i Miro:
https://miro.com/app/board/uXjVOOl_P6I=/?invite_link_id=988543907146

### Bakgrunn
Reisesøk er under arbeid og i den forbindelse tar vi i bruk OTP2 og JP3. Det er ønskelig å skaffe innsikt i hvordan reiseforslagene i JP3 er sammenlignet med JP2, slik at vi med mindre risiko kan vurdere å rulle ut OTP2/JP3 til alle.

Tor, Simen og Hilde har hatt planleggingsmøte og vurdert hvordan vi kan sørge for å få innsikt i dette fra ulike vinkler (11. jan).

### Notater
- De "rare" reiseforslagene fra OTP1 fra Intercom har vist seg å være like gode eller bedre i OTP2

### Spørsmål
- Dekker OTP2 godt de nok tilfellene hvor OTP1 tilsynelatende er gode på?

### Todos

- [x] @tormoseng tester ut et script for å kjøre mengdetesting på ulike typer reisesøk slik at vi får sammenlignet OTP1 og OTP2
- [x] @strombraaten Sjekker mulighetene for å hente ut data via spørreundersøkelse fra markedsanalyse om hva de reisende syns er viktig for å vurdere om et reiseforslag er relevant
- [ ] @hildeor @strombraaten Oppretter segment og klargjør melding for utsending i Intercom - dette for å starte å hente litt kvalitativ feedback på første release av eksperimentell reisesøk.
- [x] Opprette segment
- [x] Send melding til segment ang Avganger

**Comment by strombraaten** [comment]
Har tatt kontakt med Inga fra markedsanalyse, for å høre om det enten er gjort noen undersøkelser på det her fra før av, eller om hva vi kan få til i den nærmeste framtida. Venter på svar.

Går videre med å se på tekst til intercom-melding.

**Comment by hildeor** [comment]
Opprettet segment i Intercom. Releasen kommer til å inneholde både avganger og reisesøk-betaversjoner så gruppen overlapper mellom disse.

**Comment by strombraaten** [comment]
Huhei! Det er faktisk gjort en del statistikkarbeid på det her fra før av. Og det virker da definitivt ut som noe vi kan bruke for å vurdere reiseforslag.

For [i følge en undersøkelse](https://atbno.sharepoint.com/:b:/s/s_marstat/ER0wheUu61dMr1KdPvElTacBxNTZTqnhr3zwFXvWnecbow?e=0j7rrp) som Markedsanalysegjengen gjorde tidligere så virker det som **total reisetid** (1. pri) og **færrest mulig bytter** (2. pri) er det folk prioriterer høyest.

Skal nevnes at dette er svar gitt i sammenheng med spørsmålet _"Hva skal til for å la bilen stå"_ (og heller reise kollektivt).

**Fra konklusjonen i rapporten:**
> De motivasjonsfaktorene flest er enige i at skal til for at de vil bilen stå er reisetid, antall avganger, pris og ingen bytter. Deretter kommer avstand til holdeplass og punktlighet/pålitelighet.

<img width="819" alt="Skjermbilde 2022-01-13 kl  13 39 51" src="https://user-images.githubusercontent.com/72508979/149333158-ec2c2b58-21c9-457b-b657-c27bdc1c2d62.png">

<img width="1171" alt="Skjermbilde 2022-01-13 kl  13 34 49" src="https://user-images.githubusercontent.com/72508979/149331146-e347c0d6-5a61-4b7f-ad79-cd21c4a2bd7a.png">

### Byttetid
50% svarte også at 3-5 minutter var sweetspotten på byttetid, helst ikke mer eller mindre. Det var bare 8% av de som ble spørt som var komfortabel med byttetid på mindre enn 2 min, og 23% som foretrakk 8-10 minutter. Det her vil nok variere ut fra hvor du kommer fra, og lengden på reisen. Kommer du fra Klæbu f. Eks er du nok villig og vant til å vente litt lenger enn dem som kommer fra Bakklandet.

### Antall bytter
Kan ikke se at dette blei nevnt i rapporten, men ut fra diskusjonen vi hadde så blei det nevnt at ett bytte er greit nok, men dersom det blir flere bytter så var det mer ønskelig med forlenga reisetid, framfor å bytte enda en gang.

---

Diskuterte det kort på Slack med @hildeor, som foreslo at vi kunne "sortert på **kortest reisetid**, basert på den innsikten der, og hvis det går an å skru på at andre pri er antall bytter".

**Comment by strombraaten** [comment]
La til link i beskrivelsesteksten til [en Miro-tavle](https://miro.com/app/board/uXjVOOl_P6I=/?invite_link_id=988543907146) som samler sammen innsikten vi finner fortløpende.

**Comment by strombraaten** [comment]
Diskuterte det her med @hildeor og @magnusolderoesaether her om dagen, om arbeidet med å sammenligne otp1 og otp2. Konklusjonen i den diskusjonen var at det handler egentlig ikke om otp2 er bedre enn otp1 eller ikke, for vi må uansett bytte. Så da handler det mer om **hvordan gjør vi det beste ut av otp2 med de parametrene vi kan justere på.**

Da kommer vi i så fall inn på det her med [personlige preferanser](https://github.com/AtB-AS/mittatb-app/issues/956), filtrere reisesøk, og om vi kan tilby et slags "smart reiseforslag" som f. Eks kan luke ut mindre relevante alternativer som å gå i 56 minutter fra Rotvoll, i stedet for å vente på bussen. 

Basert på testene som @tormoseng [har kartlagt i Miro](https://miro.com/app/board/uXjVOOl_P6I=/?moveToWidget=3458764518410788642&cot=14) så virker det som konklusjonen er at otp2 virker like bra, eller bedre, enn otp1, (med noen rare unntak her og der), vil du ikke si det? I så fall, så foreslår jeg at vi lukker denne saken og lager en ny som spisser seg mer mot hvordan vi kan forbedre reiseforslagene basert på de parametrene vi kan justere på. Eller eksisterer det noe fra før av som vi kan bygge videre på? Leita gjennom istad og kunne ikke finne noe som passa 🤔

**Comment by hildeor** [comment]
https://github.com/AtB-AS/mittatb-app/issues/2260

**Comment by tormoseng** [comment]
#2283
