### ISSUE TITLE
QA v1.15

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2089]
En oversikt over saker som har fremkommet under QA-prosessen (siden 13.januar).

Merk av for hvert underpunkt når en sak er fikset / tilgjengelig i test / testet. Selve saken sjekkes ut når alle underpunkter er ferdige.

- [x] App kræsjer ved åpning av reiseforslag ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1642060158012400))
    - [x]  Fikset av #1848 
    - [x] Tilgjengelig for test
    - [x] Testet OK
 - [x] Mangler padding mellom korrespondanse-infoboksen og delen av reisen som kommer under ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643183607001300))
     - [x] Fikset @monopoint 
     - [x] Tilgjengelig for test @monopoint 
     - [x] Testet OK @hildeor 
 - [x] Mye padding mellom søkefelt og resultater. Ingen regresjonsfeil, opprettet sak. ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643185288001600)).
     - [x] Opprettet sak #2077 @gorandalum
- [x] HTTP 401 på GET /tokens gir kræsj på Android og problemer med QR-kode ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643188590003100))
    - [x] Fikset av https://github.com/AtB-AS/abt-tokens/pull/25
    - [x] Tilgjengelig for test
    - [x] Testet OK @tormoseng 
- [x] Opplevelsen av å hente inn flere reiseforslag er veldig treig ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643203958012000))
    - [x] Fikset av Enturs implementasjon av automatisk søkevindu
    - [x] Tilgjengelig for test
    - [x] Testet OK @hildeor 
- [x] Fikse padding på transport-ikon ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643272702018900))
    - [x] Fikset i #2074 
    - [x] Tilgjengelig for test @gorandalum 
    - [x] Testet OK @hildeor 
- [x] Tisdpunkt oppdateres ikke for søketidspunkt i reisesøk v2 ([Slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1643201571208600?thread_ts=1643182295.181200&cid=C02EEG7D8EL))
    - [x] Fikset av #2073 
    - [x] Testet OK @tormoseng 
- [x] Mangler padding mellom ulike dager i reisesøk v2 ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643274950027000))
    - [x] Fikset? @monopoint 
    - [x] Tilgjengelig i test @monopoint 
    - [x] Testet OK @hildeor  
- [x] Uthenting av linjenummer for Fly viser "null" ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643282607031400))
    - [x] Fikset? @monopoint 
    - [x] Tilgjengelig i test @monopoint 
    - [x] Testet OK @hildeor 
- [x] Ghost legs av og til. både på OTP 1 og 2 ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643289343050800))
    - [x] Fikses senere i sak #2079 
- [x] Feil på reisesøk (a.k.a 502 og 504) ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643293518059700))
    - Skyldes sannsynligvis ustabilitet hos Entur. Må testes i Prod. 
    - [x] Opprette sak for ikke å JSON-parse feilresponser: #2111 
    - [x] Re-test i Prod etter BFF-deploy @hildeor @tormoseng 
    - [x] Overfør dette punktet til QA v1.16 slik at vi er klar over problemstillingen også der

## Flyttes til QA v1.16 #2112 

- Fra og Til endres tilbake til tidligere søk under lasting av reiser (a.k.a Hilde-bug) ([Slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1643182295181200))
    - Opprettet egen sak som tar denne videre #2113
- Reisesøk oppdaterer seg kontinuerlig uten brukerinput (loop) (a.k.a Hilde-bug) ([Slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1643185889192100?thread_ts=1643182295.181200&cid=C02EEG7D8EL))
    - Opprettet egen sak som tar denne videre #2113
- Når et reiseforslag blir langt blir det visuelt kuttet uten at det er mulighet for å scrolle horisontalt ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643288458048400))
    - Fikses i sak #2114   
- Mange duplikate reiseforslag ved å velge Ankomst før ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643362553448509))
    - Fikses i sak #2115
- Duplikate ServiceJourney IDer (ex T-banen i Oslo) på Avganger v2 ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643371819387409))
    - Fikses i sak https://github.com/AtB-AS/mittatb-app/issues/2090
    - Tilgjengelig i test @rosvik 
    - Testet OK

**Comment by hildeor** [comment]
Foreslår at vi lager en egen issue på det med at reiseforslagene blir visuelt kuttet/konflikt mellom klikkeflate og scroll

**Comment by tormoseng** [comment]
Alle aktuelle saker er sjekket ut, og gjenværende er flyttet til #2112.
