### ISSUE TITLE
QA v1.18: Billettering 2.0. part 1 + tilbakemld.komp

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2556]
## Innledning

En oversikt over saker som må testes i QA for v1.18, og observasjoner gjort under testing av v1.18.

Merk av for hvert underpunkt når en sak er fikset / tilgjengelig i test / testet. Selve saken sjekkes ut når alle underpunkter er ferdige.

## Tidligere versjoner
- #2089 
- #2112 
- #2211 

## Observasjoner som må tas for v1.18

- [x] Skjermleser for Android leser ikke opp alternativene for tilbakemeldingskomponenten ([lenke](https://github.com/AtB-AS/mittatb-app/issues/2345#issuecomment-1109481192)) Løses her: https://github.com/AtB-AS/mittatb-app/pull/2572
- [x] iOS: Feil fokusrekkefølge på Sist kjøpte billetter: hele øverste halvdel (utenom Gjenta-knappen) kunne vært ett fokusområde, deretter må fokuset flyttes til tilhørende knapp. Se. feks på knappene for billettprodukter for eksempel på hvordan det er slått sammen til ett element. Slik det er implementert på Sist kjøpte nå så flyttes fokus mellom alle ulike «sist kjøpte» elementer, i stedet for å ta 1. første innholdsblokk 2. knapp som tilhører første innholdsblokk. Pass også på at f. eks labelen «sone» og verdien «A» leses opp sammen: «Sone», «A». @toretefre Løses her: https://github.com/AtB-AS/mittatb-app/pull/2567
- [x] Sist kjøpte: Bygger på den over. På iOS får nå hele billettinnholdet fokus med riktig opplesning, mens neste fokus blir neste billetts innhold og ikke "Gjenta kjøp" knappen. På Android er det bra.
- [x] Android: Bygger på det @hildeor nevner over, men her så leses i tillegg bussikonet opp som "buss", og "BUSS/TRIKK" leses opp bokstav for bokstav. @toretefre Løses også her: https://github.com/AtB-AS/mittatb-app/pull/2567
- [x] iOS: På nye kjøpsknapper (Alle billetter): Nå leser den opp innholdet i knappene (veldig fint) men savner hjelp til å forstå at det er en knapp/lenke jeg kan aktivere for å gå videre til kjøpsprosessen. Kunne for eksempel lagt til noe a la «Aktiver for å gå videre til kjøp» eller noe? @monopoint 
    - Bare en notis her: Android leser opp "dobbeltrykk for å aktivere", noe iOS ikke gjør. 
    - https://github.com/AtB-AS/mittatb-app/pull/2570
- [x] Feil farge på "ChatUnread"-ikonet i header (ikon av når man har fått en melding fra Intercom). @rosvik 
	- https://github.com/AtB-AS/design-system/pull/40
	- https://github.com/AtB-AS/mittatb-app/pull/2575
- [x] Sist kjøpte: Tekststørrelse på transportmiddel er større enn på Alle billetter. Sjekk skriftstørrelse på Reisende og Sone også. @toretefre 
- [x] Sist kjøpte: Pil-ikon på knapp er svart i stedet for hvitt (i light mode) @toretefre 
- [x] Sist kjøpte: Litt for lite padding mellom “Enkeltbillett” og “Reisende/sone”. @toretefre 
- [x] Sist kjøpte: Farge på skrift: Reisende og sone skal være ny secondary-tekstfarge @toretefre 
- [x] Sist kjøpte: Noen ganger står det “1 Voksen” med stor V, mens på en annen står det “1 voksen” med liten V. Vet ikke om dette er noe nytt? @toretefre 
- [x] Alle billetter: Farge på ikonene skal være ny Text/Secondary-farge @monopoint 
- [x] Alle billetter: Er det litt for liten padding mellom “Gyldig i 90 min blabla” og ikonet under? @monopoint 
- [x] Generelt: Ser ut som ikonene for transportmiddel er litt for store i størrelse? Både Alle billetter og sist kjøpte @monopoint 
- [x] Alle billetter: Er skriftfarge på “buss/trikk” #000 (text primary) nå? - bare dobbeltsjekk @monopoint 
  - Ja, og stilen kommer fra design systemet. Ser rett ut på android. skjermbilde på ios? 
- [x] Aktive billetter-fane: Buss-ikon har forsvunnet fra periodebillett, aktive billetter-fanen @rosvik 
	- https://github.com/AtB-AS/mittatb-app/pull/2579
- [x] Sist kjøpte: Loading-spinner er hvit på lys bakgrunn og nesten usynlig (i hvert fall på android) @toretefre  
- [x] "Ikke vis dette spørsmålet igjen" på tilbakemeldingskomp er i hvit skrift på light mode @rosvik  
	- https://github.com/AtB-AS/mittatb-app/pull/2587
- [x] Feil farger på aktive og brukte klipp på klippekort @rosvik 
	- https://github.com/AtB-AS/mittatb-app/pull/2580 
- [x] Forsidebildet mangler på iOS 
- [x] Align ikoner på Alle billetter horisontalt, uavhengig av tekstlengde
- [x] Juster skriftstørrelse på "1 voksen", "A" til tertiary
- [x] Juster skriftstørrelse på "+2 andre" til tertiary
- [x] Gjenta kjøp-knapp mangler engelsk oversettelse
- [x] Siste kjøp: skjermleser leser opp "1 voksen" uavhengig av antallet voksne som står der. Har man valgt flere reisendekategorier så leses alle opp som bare "1", selv om alle inneholder f.ex "2".
- [x] Alle billetter: Fjerne ScrollView ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1651226371397699))

## Saker som må testes i Staging

- [x] Skjermleser iOS/Android på tilbakemeldingskomponenten
- [x] Skjermleser iOS/Android på ny billettkjøpsside (både sist kjøpte og innganger til kjøp)
- [x] Billettering 2.0
    - [x] Ny struktur fungerer for kjøp
    - [x] Siste kjøp blir riktig
    - [x] Valg av siste kjøp leder til kjøpsprosessen med riktig info
- [x] Farger og ikoner er riktige @hildeor 

## Saker som må testes i Prod

- [x] Verifiser at informasjon fra Firestore vises riktig (ref #2430 og #2475)
- [x] Reisesøk
    - [x] Test #2499 
    - [x] Enkel regresjonstest utover punktet over
- [x] Avganger
    - [x] Test #2499 
    - [x] Enkel regresjonstest av v1 og v2 utover punktet over
- [x] Billettkjøp
    - Regresjonstest av enkeltbillett og periodebillett med/uten lagret betalingskort + Vipps
    - Verifiser at siste kjøp blir riktig og valg leder til riktig kjøp
    - Sjekk samtidig at man får et mob.token og kan toggle mellom ulike devicer og t:kort

**Comment by toretefre** [comment]
Da ligger de tre øverste oppgavene på `Observasjoner som må tas for v1.18` inne med linker til pull request som fikser.

**Comment by tormoseng** [comment]
Alt er testet og 1.18 sendes til Prod 05.05.
