### ISSUE TITLE
[Deployment] v1.5 discussion

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#859]
This is a format I'd like to introduce for crystalizing what's left and needed TODOs before we can publish.

# Version goals

- [i18n] A first pass at English translation, and enabling it in profile (feature flag)
- [Ticketing] Releasing a stable version of ticketing which can be used by first closed beta group 
- [Ticketing] Partly updating ticketing screens to new design (quick win design)
- [Ticketing] A fix for refunded tickets so they do not show up as valid tickets

# TODOs

## Store-related
- [x] Version bump to v1.5 (#858)
- [x] Snip a version for alpha-release to go through beta review
- [ ] Create new store versions
- [ ] Update store localization with English texts
- [ ] (Optional) Update store assets/text/screenshots

## Features/fixes
- [x] Finalize a first pass at English translations (#846)
- [x] Refunded tickets fix (#853)
- [x] #855 More robust fetching of fare contracts
- [x] #862 Add feature toggle for ticket purchasing so we can force users to upgrade if needed
- [x] #856 Fix product/zone/user names on ticket
- [x] #857 Update counter-input to new design 
- [x] #849 Add feature toggle for pay with creditcard

**Comment by mikaelbr** [comment]
This can be closed now, @cbrevik ?
