### ISSUE TITLE
[Deployment] v1.6 discussion

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#869]
Issue for discussing what to include in the next version. This is not supposed to be a changelog or complete backlog. It is used primarily as a working document for deciding scope.

# Version goals/scope

- Ny infrastruktur for håndtering av billetter (Firestore)
- Åpen pilot billettering enkeltbillett (etter QA av Firestore)
- Periodebilletter (feature toggled)
- Telefoninnlogging via SMS (feature toggled)
- Inspeksjon via QR (basic uten mobile token)
- Siste kjøp under billettering
- Visning av melding ved driftsproblemer
- Visuell inspeksjon for bussjåfører utenfor Stor-Trondheim
- ~Enkel form for passasjertelling (historisk data/prognoser)~

# TODOs

## Store-related
- [x] Version bump to v1.6
- [x] Snip a version for alpha-release to go through beta review
- [x] Create new store versions
- [ ] (Optional) Update store assets/text/screenshots

## Features/fixes
- [x] feat: Logging in with phone #934 
- [x] feat: New purchase flow for period ticket #928

**Comment by cbrevik** [comment]
I've edited the main comment to reflect the situation as is. Would be cool if you could take a look and optionally discuss here or edit the comment directly if there's something I've missed @mikaelbr @gorandalum @vidtil

**Comment by mikaelbr** [comment]
Want this to be included: https://github.com/AtB-AS/mittatb-app/pull/989
