### ISSUE TITLE
[Feature] Show simple historic passenger count (passasjertelling)

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#963]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

_A short description of what user needs or business goals this feature will solve._

> Som en reisende med særskiltebehov til plass, enten det er tetthet for Covid-19, rullestol, barnevogn eller ønske om å ta med sykkel, ønsker jeg bedre grunnlag til å vurdere hvilken reisemetode og buss jeg burde ta.﻿

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Tasks

- [ ] Initial design
- [ ] Setup SQL Standard Database
- [ ] Implement first version in App.
- [ ] Validate value/confirm hypotheses

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by mikaelbr** [comment]
What's the progress on this? is the SQL populated, @monopoint ?

**Comment by mikaelbr** [comment]
Data structure specified for SQL schema

<img width="627" alt="Screenshot 2021-04-07 at 12 23 28" src="https://user-images.githubusercontent.com/606374/113851705-10f33a00-979c-11eb-8cc3-016596c38540.png">

**Comment by mikaelbr** [comment]
>>> For et tidlig eksperiment for fyllingsgrad i app ønsker vi å vise graderinger på 2 nivå:
Fyllingsgrad for en spesifikk avgang på en holdeplass.
Utvikling av fyllingsgrad for hele turen for å se om turen blir full etterhvert.

**Comment by mikaelbr** [comment]
Alternative mockups for design exploration

![image (5)](https://user-images.githubusercontent.com/606374/113852323-befee400-979c-11eb-9aa4-2b2c70eb4c92.png)

**Comment by mikaelbr** [comment]
See concept details: https://miro.com/app/board/o9J_laCOLXM=/
